// <auto-generated />
using System;
using AdvertismentPlatform.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvertismentPlatform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200302120026_UpdateModels")]
    partial class UpdateModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AdvertismentPlatform.Models.Advertisment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("advertisments");
                });

            modelBuilder.Entity("AdvertismentPlatform.Models.ItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdvertismentId")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<double?>("Price")
                        .HasColumnType("double");

                    b.Property<DateTime?>("ProductAge")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("item_type")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("AdvertismentId")
                        .IsUnique();

                    b.ToTable("items");

                    b.HasDiscriminator<string>("item_type").HasValue("ItemCategory");
                });

            modelBuilder.Entity("AdvertismentPlatform.Models.AutoItem", b =>
                {
                    b.HasBaseType("AdvertismentPlatform.Models.ItemCategory");

                    b.Property<string>("Car_Type")
                        .HasColumnType("varchar(2) CHARACTER SET utf8mb4")
                        .HasMaxLength(2);

                    b.Property<int?>("Doors")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.Property<int?>("Seats")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.ToTable("items");

                    b.HasDiscriminator().HasValue("auto_type");
                });

            modelBuilder.Entity("AdvertismentPlatform.Models.BikeItem", b =>
                {
                    b.HasBaseType("AdvertismentPlatform.Models.ItemCategory");

                    b.Property<int?>("TopSpeed")
                        .HasColumnType("int")
                        .HasMaxLength(3);

                    b.ToTable("items");

                    b.HasDiscriminator().HasValue("bike_type");
                });

            modelBuilder.Entity("AdvertismentPlatform.Models.ItemCategory", b =>
                {
                    b.HasOne("AdvertismentPlatform.Models.Advertisment", "Advertisment")
                        .WithOne("Item")
                        .HasForeignKey("AdvertismentPlatform.Models.ItemCategory", "AdvertismentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
